# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Akaash S S"
title_separator          : "-"
name                     : &name "Akaash S S"
description              : &description "B.Tech Mechanical Engineering student at IIT Guwahati | Robotics & EV Enthusiast"
url                      : "https://akaashss.github.io"
baseurl                  : ""
repository               : "akaashss/akaashss.github.io"

# Site Author (sidebar info)
author:
  avatar           : "profile.png"   # put a square image in /images/ or /assets/img/
  name             : "Akaash S S"
  pronouns         : 
  bio              : "B.Tech Mechanical Engineering @ IIT Guwahati. Interests: Robotics, EVs, and automation."
  location         : "IIT Guwahati, India"
  employer         : 
  email            : "your.email@example.com"

  # Academic websites
  googlescholar    : # add when you have one
  orcid            : 
  researchgate     : 

  # Repositories
  github           : "akaashss"

  # Social media
  linkedin         : "akaash-ss"     # put your LinkedIn username
  twitter          : 
  instagram        : 

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
breadcrumbs              : false
words_per_minute         : 160
read_more                : "disabled"
talkmap_link             : false

# Analytics (optional)
analytics:
  provider               : "false"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
